"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const path_1 = __importDefault(require("path"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
const pages_1 = require("./routes/pages");
const login_1 = require("./routes/login");
const signup_1 = require("./routes/signup");
const app = (0, express_1.default)();
app.set("view engine", 'ejs');
app.use(express_1.default.static(path_1.default.join(__dirname, "public")));
app.use(express_1.default.urlencoded({ limit: '50mb', extended: true }));
app.use(express_1.default.json({ limit: '50mb' }));
app.use((0, cookie_parser_1.default)());
app.use("/", pages_1.pagesRoute);
app.use("/", login_1.loginRoute);
app.use("/", signup_1.signupRoute);
app.listen(80);
