"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const path_1 = __importDefault(require("path"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
const pages_1 = require("./routes/pages");
const logon_1 = require("./routes/logon");
const logout_1 = require("./routes/logout");
const friendreqsts_1 = require("./routes/friendreqsts");
const userrequests_1 = require("./routes/userrequests");
const friends_1 = require("./routes/friends");
const app = (0, express_1.default)();
app.set("view engine", 'ejs');
app.use(express_1.default.static(path_1.default.join(__dirname, "public")));
app.use(express_1.default.urlencoded({ limit: '50mb', extended: true }));
app.use(express_1.default.json({ limit: '50mb' }));
app.use((0, cookie_parser_1.default)());
app.use("/", pages_1.pagesRoute);
app.use("/", logon_1.logonRoute);
app.use("/fr", friendreqsts_1.friendRequestsRoute);
app.use("/logout", logout_1.logoutRoute);
app.use("/user", userrequests_1.userRequestRoute);
app.use("/friends", friends_1.friendsRoute);
app.listen(80);
